// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplicationOperaLublin.Contexts;

#nullable disable

namespace WebApplicationOperaLublin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241202173622_UserLoginAttempt")]
    partial class UserLoginAttempt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("performance_id_seq");

            modelBuilder.HasSequence<int>("user_id_seq");

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genre_pk");

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreaksCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("breaks_count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time without time zone")
                        .HasColumnName("duration");

                    b.Property<int>("Genre")
                        .HasColumnType("integer")
                        .HasColumnName("genre");

                    b.Property<byte[]>("MainImage")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("main_image");

                    b.Property<int>("Place")
                        .HasColumnType("integer")
                        .HasColumnName("place");

                    b.Property<byte[]>("Poster")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("poster");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("perfomances_id_pk");

                    b.HasIndex("Genre");

                    b.HasIndex("Place");

                    b.ToTable("performance", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceDatesTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimePerformance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketsCount")
                        .HasColumnType("integer");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("performance_dates_tickets");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceDirector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("PerformanceId");

                    b.ToTable("PerformanceDirectors");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("place_id_pk");

                    b.ToTable("place", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<int>("LoginAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("user_id_pk");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Performance", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Genre", "GenreNavigation")
                        .WithMany("Performances")
                        .HasForeignKey("Genre")
                        .IsRequired()
                        .HasConstraintName("perfomance_genre_id_fk");

                    b.HasOne("WebApplicationOperaLublin.Models.Place", "PlaceNavigation")
                        .WithMany("Performances")
                        .HasForeignKey("Place")
                        .IsRequired()
                        .HasConstraintName("perfomance_place_id_fk");

                    b.Navigation("GenreNavigation");

                    b.Navigation("PlaceNavigation");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceDirector", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Director", "DirectorNavigation")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationOperaLublin.Models.Performance", "PerformanceNavigation")
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectorNavigation");

                    b.Navigation("PerformanceNavigation");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Genre", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Place", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
