// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplicationOperaLublin.Contexts;

#nullable disable

namespace WebApplicationOperaLublin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630143548_FixUniqueForEventArtist")]
    partial class FixUniqueForEventArtist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("artist_id_seq");

            modelBuilder.HasSequence<int>("event_artist_id_seq");

            modelBuilder.HasSequence<int>("main_page_background_id_seq");

            modelBuilder.HasSequence<int>("news_id_seq");

            modelBuilder.HasSequence<int>("performance_event_id_seq");

            modelBuilder.HasSequence<int>("performance_id_seq");

            modelBuilder.HasSequence<int>("public_comment_id_seq");

            modelBuilder.HasSequence<int>("section_id_seq");

            modelBuilder.HasSequence<int>("ticket_price_group_id_seq");

            modelBuilder.HasSequence<int>("ticket_price_id_seq");

            modelBuilder.HasSequence<int>("user_id_seq");

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)")
                        .HasColumnName("description");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("last_name");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("artist_id_pk");

                    b.ToTable("artist", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.ArtistPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("artist_photo", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.EventArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("EventId");

                    b.ToTable("event_artist", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genre_pk");

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Implementer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDirector")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("implementer");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.MainPageBackground", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("MainImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("main_page_background", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<byte[]>("MainImage")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("main_image");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("news_id_pk");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("BreaksCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("breaks_count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time without time zone")
                        .HasColumnName("duration");

                    b.Property<int>("Genre")
                        .HasColumnType("integer")
                        .HasColumnName("genre");

                    b.Property<byte[]>("MainImage")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("main_image");

                    b.Property<int>("Place")
                        .HasColumnType("integer")
                        .HasColumnName("place");

                    b.Property<byte[]>("Poster")
                        .HasColumnType("bytea")
                        .HasColumnName("poster");

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("premiere_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("perfomances_id_pk");

                    b.HasIndex("Genre");

                    b.HasIndex("Place");

                    b.ToTable("performance", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StartAt");

                    b.HasIndex("PerformanceId", "StartAt")
                        .IsUnique();

                    b.ToTable("performance_event", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceImplementer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImplementerId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImplementerId");

                    b.HasIndex("PerformanceId");

                    b.ToTable("performance_implementer");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformancePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PerformanceId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.ToTable("performance_photo", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("place_id_pk");

                    b.ToTable("place", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PublicComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsShowing")
                        .HasColumnType("boolean");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.ToTable("public_comment", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("section_id_pk");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("section", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.TicketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TicketPriceGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketPriceGroupId", "Type")
                        .IsUnique();

                    b.ToTable("ticket_prices", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.TicketPriceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId", "SortOrder");

                    b.ToTable("ticket_price_groups", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastLoginAttemptTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<int>("LoginAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("user_id_pk");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.ArtistPhoto", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Artist", "ArtistNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistNavigation");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.EventArtist", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Artist", "Artist")
                        .WithMany("EventArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationOperaLublin.Models.PerformanceEvent", "PerformanceEventNavigation")
                        .WithMany("EventArtists")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("PerformanceEventNavigation");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Performance", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Genre", "GenreNavigation")
                        .WithMany("Performances")
                        .HasForeignKey("Genre")
                        .IsRequired()
                        .HasConstraintName("perfomance_genre_id_fk");

                    b.HasOne("WebApplicationOperaLublin.Models.Place", "PlaceNavigation")
                        .WithMany("Performances")
                        .HasForeignKey("Place")
                        .IsRequired()
                        .HasConstraintName("perfomance_place_id_fk");

                    b.Navigation("GenreNavigation");

                    b.Navigation("PlaceNavigation");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceEvent", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Performance", "Performance")
                        .WithMany("PerformanceEvents")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceImplementer", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Implementer", "Implementer")
                        .WithMany("PerformanceImplementers")
                        .HasForeignKey("ImplementerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationOperaLublin.Models.Performance", "Performance")
                        .WithMany("PerformanceImplementers")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Implementer");

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformancePhoto", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Performance", "PerformanceNavigation")
                        .WithMany("PerformancePhotos")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformanceNavigation");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PublicComment", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Performance", "Performance")
                        .WithMany("PublicComments")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.TicketPrice", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.TicketPriceGroup", "Group")
                        .WithMany("Prices")
                        .HasForeignKey("TicketPriceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.TicketPriceGroup", b =>
                {
                    b.HasOne("WebApplicationOperaLublin.Models.Performance", "Performance")
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Artist", b =>
                {
                    b.Navigation("EventArtists");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Genre", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Implementer", b =>
                {
                    b.Navigation("PerformanceImplementers");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Performance", b =>
                {
                    b.Navigation("PerformanceEvents");

                    b.Navigation("PerformanceImplementers");

                    b.Navigation("PerformancePhotos");

                    b.Navigation("PublicComments");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.PerformanceEvent", b =>
                {
                    b.Navigation("EventArtists");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.Place", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("WebApplicationOperaLublin.Models.TicketPriceGroup", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
